inputs:
  php-version:
    description: |
      Specifies the version of php to use.
    required: false
    default: 8.0.16
  phpstan-version:
    description: |
      Specifies the version of phpstan to use.
    required: false
    default: latest
  pmmp-version:
    description: |
      Specifies the version of pmmp source to analyse against.
    required: false
    default: latest
  pmmp-source-dir:
    description: |
      Specifies the directory to install pmmp sources to.
    required: false
    default: "./pocketmine"
  analyse:
    description: |
      A space seperated list of paths to analyse.
    required: false
    default: undefined
  level:
    description: |
      Specifies the rule level to run. https://phpstan.org/user-guide/rule-levels

      Possible values: 1-9
    required: false
    default: 9
  config:
    description: |
      Path to PHPStan configuration file. Relative paths are resolved based on the current working directory.
    required: false
    default: "./pocketmine/phpstan/phpstan.neon"
  memory-limit:
    description: |
      Specifies the memory limit in the same format php.ini accepts.
    required: false
    default: 1G
  debug:
    description: |
      Instead of the progress bar, it outputs lines with each analysed file before its analysis.
    required: false
    default: "false"
  quiet:
    description: |
      Silences all the output. Useful if you’re interested only in the exit code.O
    required: false
    default: "false"
  autoload-file:
    description: |
      If your application uses a custom autoloader, you should set it up and register in a PHP file that is
      passed to this CLI option. Relative paths are resolved based on the current working directory.
    required: false
    default: ""
  error-format:
    description: |
      Specifies a custom error formatter. https://phpstan.org/user-guide/output-format
    required: false
    default: github
  ansi:
    description: |
      Overrides the auto-detection of whether colors should be used in the output and how nice the progress bar should be.
    required: false
    default: "true"

name: Setup PHPStan
description: GitHub action for setting up PHPStan in an actions environment.
author: NxtLvLSoftware Solutions
branding:
  icon: settings
  color: blue
runs:
  using: composite
  steps:
    - name: Build and prepare PHP cache
      uses: pmmp/setup-php-action@aa636a4fe0c1c035fd9a3f05e360eadd86e06440
      with:
        php-version: ${{ inputs.php-version }}
        install-path: "./bin"
    - name: Install and prepare PHPStan
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      uses: ./setup-phpstan
      with:
        version: ${{ inputs.phpstan-version }}
        install-path: "./bin/phpstan"
    - name: Setup PMMP Sources
      uses: ./setup-pmmp-phpstan-env
      with:
        pmmp-version: ${{ inputs.pmmp-version }}
        install-path: ${{ inputs.pmmp-source-dir }}
    - name: Display structure of downloaded files
      shell: bash
      run: cd pocketmine && ls -R && cat ./phpstan/rules/DisallowEnumComparisonRule.php
    - id: vars
      uses: juliangruber/read-file-action@v1
      with:
        path: pocketmine/phpstan/rules/DisallowEnumComparisonRule.php
    - shell: bash
      run: echo "${{ steps.vars.outputs.content }}"
    - name: Run PHPStan analysis
      uses: ./run-phpstan
      with:
        executable: "./bin/phpstan/phpstan.phar"
        php: "./bin/bin/php"
        analyse: ${{ inputs.analyse }}
        level: ${{ inputs.level }}
        config: ${{ inputs.config }}
        memory-limit: ${{ inputs.memory-limit }}
        debug: ${{ inputs.debug }}
        quiet: ${{ inputs.quiet }}
        autoload-file: ${{ inputs.autoload-file }}
        error-format: ${{ inputs.error-format }}
        ansi: ${{ inputs.ansi }}
